container_image = docker://quay.io/biocontainers/agat:1.4.2--pl5321hdfd78af_0

executable = GFF2GTF.sh

## CHANGE THIS ##
staging = /staging/p/ptran5/rnaseq
ref = RN4220withTarget
# no file extension please

arguments = $(ref)

log = logs/gff2gtf_$(ref).log
error = logs/gff2gtf_$(ref).err
output = logs/gff2gtf_$(ref).out

transfer_input_files = file://$(staging)/input/$(ref).gff
transfer_output_files = $(ref).gtf
transfer_output_remaps = "$(ref).gtf=file://$(staging)/input/$(ref).gtf"

requirements = (HasCHTCStaging == true)

request_cpus = 8
request_memory = 16GB
request_disk = 30GB      

queue
